#!/usr/bin/env bash

function getContainerId {
	docker ps | grep $1 | cut -d ' ' -f 1
}

function getIp {
	docker inspect --format '{{ .NetworkSettings.IPAddress }}' $1
}


function printInfo {
	local NAME=$1
	local SEARCH=$2

	CONTAINER_ID=$(getContainerId $SEARCH)
	IP=$(getIp $CONTAINER_ID)

	echo "$NAME"
	echo "-------------------------------------"
	echo "Container ID: $CONTAINER_ID"
	echo "IP: $IP"
}



printInfo 'Mongo' 'shh-mongo'

echo ""
echo ""
printInfo 'API' 'pingvinen/shh-api'
